### ISSUE TITLE
Dist index.js throws error: Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by jamespsterling** [MinimalistYing/vanilla-antd-message#1]
```ant-toast.min.js:1 Uncaught ReferenceError: exports is not defined at ant-toast.min.js:1```

**Comment by MinimalistYing** [comment]
I guess you used the minified code directly from `<script>`   
This bug is fixed in the latest version  
Now you can use like `Message.default.info('Hello')`   
When you directly use the code in `<script>` tag
If the latest version still couldn't work  
Please reopen this issue to make me know, Thanks~
